import { env } from "~/env";
export const USDC_ASSET_CODE = env.NEXT_PUBLIC_STAGE === "prod" ? "USDC" : "TestUSDC";
export const USDC_ISSUER = env.NEXT_PUBLIC_STAGE === "prod" ? "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN" : "GBKNCC42V7X6KOU6UW5WVEZMLJIUB7WBXWINXC6LPF66EGWW6LYJKHOC"