/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "BEARER_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GEMINI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GenerationJobs": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Hono": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}