-- AlterTable
ALTER TABLE "Creator"
ADD COLUMN "coverHeightDefault" INTEGER NOT NULL DEFAULT 240,
ADD COLUMN "coverHeightDesktop" INTEGER NOT NULL DEFAULT 240,
ADD COLUMN "coverHeightMobile" INTEGER NOT NULL DEFAULT 220;
